################################################################################
#
# THIS FILE IS BASIC MAKE FILE FOR
# Copyright (c) 2020-2021
# Original Author: 1107473010@qq.com
#
################################################################################

# This is object should be build and will link to generate
# the executable or staticLibrary
Objects = mongoose.o

IncludePath = 

Defines = 

# This is the file name of the executables and path where 
# place the executable or staticLibrary
TargetFile = libmongoose.a

# Including this file allows access to the Build System.
include ../../../../../Build/buildLibRules.mk